services:
  api:
    build:
      context: .
      dockerfile: Wealth.Api/Dockerfile
    image: wealth-api:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__ConnectionString=mongodb://mongo:27017
      - Mongo__Database=wealth
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./Wealth.Api/Data:/imports:ro
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mongo_data:/data/db
      - ./Wealth.Api/Data:/imports:ro
volumes:
  mongo_data:
